name: rise-environment
channels:
  - conda-forge
dependencies:
  - python
  - rise
  - bokeh
  - graphviz
  - ipywidgets
  - matplotlib
  - numpy
  - pandas
  - pandas-datareader
  - pydot
  - seaborn
  - scipy
  - sklearn
  - tensorflow
  - tensorflow_probability
